### PR TITLE
Made search view that so far works

### PR DESCRIPTION
**Pull request by Akonwar1**
Had to change a lot in the data model mostly making some of the classes hashable and equatable. Also messed around a lot with the placeholders.

### CODE REVIEW

**Comment by plasmium1** [comment]
Did you reintegrate this with the rest of the stuff I merged on Thursday?

**Comment by Akonwar1** [comment]
It’s all up to date and merged in the branch called test 2

**Comment by Akonwar1** [comment]
I made a mistake before committing my changes so I fixed it and redid it so
it worked

**Comment by plasmium1** [comment]
You should make a PR for test2

**Pull request closed without merging**
